### ISSUE TITLE
forms.util is used at line 23 of forms.py, I think it's a typo, supposed to be "forms.utils"

### ISSUE THREAD

**Issue by Burrito-Bazooka** [bitmazk/django-multilingual-survey#1]
"django.forms.util" doesn't seem to exist in Django, but "django.forms.utils" does. Tested on Pythons 3.2 and 2.7. I get errors when I try to run django-multilingual-survey, related to the use of "forms.util" at this line.

https://github.com/bitmazk/django-multilingual-survey/blob/ac04b3c362243bad7d3f0ae7c972e55f4b7f0340/multilingual_survey/forms.py#L23

**Comment by Tyrdall** [comment]
@Burrito-Bazooka Which django version are you using?

In Django<1.7 it is ``util``. In Django>=1.7 the it is called ``utils``. We haven't migrated our apps to 1.7 yet.

**Comment by macagua** [comment]
@Tyrdall maybe can add it:

```
try:
    # Django < 1.7.x
    from django.forms.util import ErrorList
except ImportError:
    # Django >= 1.7.x
    from django.forms.utils import ErrorList
```

And chance this: 

```
    def __init__(self, user, session_key, survey, data=None, files=None,
                 auto_id='id_%s', prefix=None, initial=None, label_suffix=':',
                 error_class=forms.util.ErrorList, empty_permitted=False):
```
By this improvement for versions Django >= 1.7.x
```
    def __init__(self, user, session_key, survey, data=None, files=None,
                 auto_id='id_%s', prefix=None, initial=None, label_suffix=':',
                 error_class=ErrorList, empty_permitted=False):

```

**Comment by Tyrdall** [comment]
@macagua Sure! Do you want to send a pull request?
