### ISSUE TITLE
`generic` no longer on  contenttypes, preventing compilation Django 1.9+

### ISSUE THREAD

**Issue by Kyle-Falconer** [bitmazk/django-multilingual-survey#3]
When trying to run the code on Django 1.9 I get the following error:

```
File "/lib/python2.7/site-packages/multilingual_survey/models.py", line 2, in <module>
    from django.contrib.contenttypes import generic
ImportError: cannot import name generic
```

It seems the `generic` package was deprecated in 1.7 and removed in 1.9 ([see the docs](https://docs.djangoproject.com/en/1.9/releases/1.9/#features-removed-in-1-9)) , moved to `django.contrib.contenttypes.fields`, so the new import statement should be:

```
try:
    # Django < 1.9.x
    from django.contrib.contenttypes.generic import GenericRelation
except ImportError:
    # Django >= 1.9.x
    from django.contrib.contenttypes.fields import GenericRelation
```
Additionally, the two references to `generic.GenericRelation` should be changed to `GenericRelation`

**Comment by Tyrdall** [comment]
Fixed in 0.3
