### ISSUE TITLE
ImportError: No module named django_libs.models_mixins

### ISSUE THREAD

**Issue by Kyle-Falconer** [bitmazk/django-multilingual-survey#4]
Based on the latest changes to fix Django 1.9 integration (thank you so much, btw!), the new code relies on bitmazk/django-libs project, so the readme should reflect this.

This should be right above `pip install django-multilingual-survey` :

```
pip install django-libs
```

**Comment by Tyrdall** [comment]
@Kyle-Falconer You're right :) Just added ``django-libs`` to the install requirements.

https://github.com/bitmazk/django-multilingual-survey/commit/7b64fd46dfefa51e2fa015927dd997c61f5b431c

Thanks for your feedback!
